############################# English ############################
[en]
languageName = "FR"
title = "Diagnostics Le Grand Paris"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Assurance & Certifications"
footer_menu_middle = "Services"
footer_menu_right = "À propos"
footer_content = "07 67 41 37 77 </br> contact@diagnostics-legrandparis.fr </br> 25 Rue des Bouleaux </br> 91140 Villebon-sur-Yvette"
# copyright
copyright = "Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"