# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Diagnostics"
url = "diagnostics"
weight = 2

[[main]]
name = "Tarifs"
url = "tarifs"
weight = 3

[[main]]
name = "Contact"
url = "contact"
weight = 4

[[main]]
name = "FAQ"
url = "faq"
weight = 5

# footer menu left
[[footer_left]]
name = "Socotec"
url = "images/logosocotec.png"

# footer menu left
[[footer_left]]
name = "FIDI"
url = "images/logofidi.png"

# footer menu left
[[footer_left]]
name = "MMA"
url = "images/logomma.png"

# footer menu middle
[[footer_middle]]
name = "Diagnostics"
url = "diagnostics"

[[footer_middle]]
name = "Tarifs"
url = "tarifs"

[[footer_middle]]
name = "FAQ"
url = "faq"

# footer menu right
[[footer_right]]
name = "Conditions Générales de Vente"
url = "conditions"

[[footer_right]]
name = "Médiation"
url = "médiation"

[[footer_right]]
name = "Mentions légales"
url = "mentions"