#################### default parameters ################################
logo = "images/logo-web-transparent blanc.png"
logo_width = "300px"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = false
label = "Get Started"
link = "contact"

  
############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/diagnosticslegrandparis"

[[social]]
title = "whatsapp"
icon = "fab fa-whatsapp" # themify icon : https://themify.me/themify-icons
link = "https://wa.me/message/ZSMJVCABYEXMC1"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"